using Microsoft.EntityFrameworkCore;
using SkillMatrix.Domain.Languages.Models;

namespace SkillMatrix.DataAccess.Seeds
{
    public static class LanguagesSeed
    {
        public static void SeedLanguages(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Language>()
                .HasData(
                    new Language { Id = 1, Code = "ab", Name = "Abkhaz", NativeName = "аҧсуа" },
                    new Language { Id = 2, Code = "aa", Name = "Afar", NativeName = "Afaraf"},
                    new Language { Id = 3, Code = "af", Name = "Afrikaans", NativeName = "Afrikaans"},
                    new Language { Id = 4, Code = "ak", Name = "Akan", NativeName = "Akan"},
                    new Language { Id = 5, Code = "sq", Name = "Albanian", NativeName = "Shqip"},
                    new Language { Id = 6, Code = "am", Name = "Amharic", NativeName = "አማርኛ"},
                    new Language { Id = 7, Code = "ar", Name = "Arabic", NativeName = "العربية"},
                    new Language { Id = 8, Code = "an", Name = "Aragonese", NativeName = "Aragonés"},
                    new Language { Id = 9, Code = "hy", Name = "Armenian", NativeName = "Հայերեն"},
                    new Language { Id = 10, Code = "as", Name = "Assamese", NativeName = "অসমীয়া"},
                    new Language { Id = 11, Code = "av", Name = "Avaric", NativeName = "авар мацӀ, магӀарул мацӀ"},
                    new Language { Id = 12, Code = "ae", Name = "Avestan", NativeName = "avesta"},
                    new Language { Id = 13, Code = "ay", Name = "Aymara", NativeName = "aymar aru"},
                    new Language { Id = 14, Code = "az", Name = "Azerbaijani", NativeName = "azərbaycan dili"},
                    new Language { Id = 15, Code = "bm", Name = "Bambara", NativeName = "bamanankan"},
                    new Language { Id = 16, Code = "ba", Name = "Bashkir", NativeName = "башҡорт теле"},
                    new Language { Id = 17, Code = "eu", Name = "Basque", NativeName = "euskara, euskera"},
                    new Language { Id = 18, Code = "be", Name = "Belarusian", NativeName = "Беларуская"},
                    new Language { Id = 19, Code = "bn", Name = "Bengali", NativeName = "বাংলা"},
                    new Language { Id = 20, Code = "bh", Name = "Bihari", NativeName = "भोजपुरी"},
                    new Language { Id = 21, Code = "bi", Name = "Bislama", NativeName = "Bislama"},
                    new Language { Id = 22, Code = "bs", Name = "Bosnian", NativeName = "bosanski jezik"},
                    new Language { Id = 23, Code = "br", Name = "Breton", NativeName = "brezhoneg"},
                    new Language { Id = 24, Code = "bg", Name = "Bulgarian", NativeName = "български език"},
                    new Language { Id = 25, Code = "my", Name = "Burmese", NativeName = "ဗမာစာ"},
                    new Language { Id = 26, Code = "ca", Name = "Catalan; Valencian", NativeName = "Català"},
                    new Language { Id = 27, Code = "ch", Name = "Chamorro", NativeName = "Chamoru"},
                    new Language { Id = 28, Code = "ce", Name = "Chechen", NativeName = "нохчийн мотт"},
                    new Language { Id = 29, Code = "ny", Name = "Chichewa; Chewa; Nyanja", NativeName = "chiCheŵa, chinyanja"},
                    new Language { Id = 30, Code = "zh", Name = "Chinese", NativeName = "中文 (Zhōngwén), 汉语, 漢語"},
                    new Language { Id = 31, Code = "cv", Name = "Chuvash", NativeName = "чӑваш чӗлхи"},
                    new Language { Id = 32, Code = "kw", Name = "Cornish", NativeName = "Kernewek"},
                    new Language { Id = 33, Code = "co", Name = "Corsican", NativeName = "corsu, lingua corsa"},
                    new Language { Id = 34, Code = "cr", Name = "Cree", NativeName = "ᓀᐦᐃᔭᐍᐏᐣ"},
                    new Language { Id = 35, Code = "hr", Name = "Croatian", NativeName = "hrvatski"},
                    new Language { Id = 36, Code = "cs", Name = "Czech", NativeName = "česky, čeština"},
                    new Language { Id = 37, Code = "da", Name = "Danish", NativeName = "dansk"},
                    new Language { Id = 38, Code = "dv", Name = "Divehi; Dhivehi; Maldivian;", NativeName = "ދިވެހި"},
                    new Language { Id = 39, Code = "nl", Name = "Dutch", NativeName = "Nederlands, Vlaams"},
                    new Language { Id = 40, Code = "en", Name = "English", NativeName = "English"},
                    new Language { Id = 41, Code = "eo", Name = "Esperanto", NativeName = "Esperanto"},
                    new Language { Id = 42, Code = "et", Name = "Estonian", NativeName = "eesti, eesti keel"},
                    new Language { Id = 43, Code = "ee", Name = "Ewe", NativeName = "Eʋegbe"},
                    new Language { Id = 44, Code = "fo", Name = "Faroese", NativeName = "føroyskt"},
                    new Language { Id = 45, Code = "fj", Name = "Fijian", NativeName = "vosa Vakaviti"},
                    new Language { Id = 46, Code = "fi", Name = "Finnish", NativeName = "suomi, suomen kieli"},
                    new Language { Id = 47, Code = "fr", Name = "French", NativeName = "français, langue française"},
                    new Language { Id = 48, Code = "ff", Name = "Fula; Fulah; Pulaar; Pular", NativeName = "Fulfulde, Pulaar, Pular"},
                    new Language { Id = 49, Code = "gl", Name = "Galician", NativeName = "Galego"},
                    new Language { Id = 50, Code = "ka", Name = "Georgian", NativeName = "ქართული"},
                    new Language { Id = 51, Code = "de", Name = "German", NativeName = "Deutsch"},
                    new Language { Id = 52, Code = "el", Name = "Greek, Modern", NativeName = "Ελληνικά"},
                    new Language { Id = 53, Code = "gn", Name = "Guaraní", NativeName = "Avañeẽ"},
                    new Language { Id = 54, Code = "gu", Name = "Gujarati", NativeName = "ગુજરાતી"},
                    new Language { Id = 55, Code = "ht", Name = "Haitian; Haitian Creole", NativeName = "Kreyòl ayisyen"},
                    new Language { Id = 56, Code = "ha", Name = "Hausa", NativeName = "Hausa, هَوُسَ"},
                    new Language { Id = 57, Code = "he", Name = "Hebrew (modern)", NativeName = "עברית"},
                    new Language { Id = 58, Code = "hz", Name = "Herero", NativeName = "Otjiherero"},
                    new Language { Id = 59, Code = "hi", Name = "Hindi", NativeName = "हिन्दी, हिंदी"},
                    new Language { Id = 60, Code = "ho", Name = "Hiri Motu", NativeName = "Hiri Motu"},
                    new Language { Id = 61, Code = "hu", Name = "Hungarian", NativeName = "Magyar"},
                    new Language { Id = 62, Code = "ia", Name = "Interlingua", NativeName = "Interlingua"},
                    new Language { Id = 63, Code = "id", Name = "Indonesian", NativeName = "Bahasa Indonesia"},
                    new Language { Id = 64, Code = "ie", Name = "Interlingue", NativeName = "Originally called Occidental; then Interlingue after WWII"},
                    new Language { Id = 65, Code = "ga", Name = "Irish", NativeName = "Gaeilge"},
                    new Language { Id = 66, Code = "ig", Name = "Igbo", NativeName = "Asụsụ Igbo"},
                    new Language { Id = 67, Code = "ik", Name = "Inupiaq", NativeName = "Iñupiaq, Iñupiatun"},
                    new Language { Id = 68, Code = "io", Name = "Ido", NativeName = "Ido"},
                    new Language { Id = 69, Code = "is", Name = "Icelandic", NativeName = "Íslenska"},
                    new Language { Id = 70, Code = "it", Name = "Italian", NativeName = "Italiano"},
                    new Language { Id = 71, Code = "iu", Name = "Inuktitut", NativeName = "ᐃᓄᒃᑎᑐᑦ"},
                    new Language { Id = 72, Code = "ja", Name = "Japanese", NativeName = "日本語 (にほんご／にっぽんご)"},
                    new Language { Id = 73, Code = "jv", Name = "Javanese", NativeName = "basa Jawa"},
                    new Language { Id = 74, Code = "kl", Name = "Kalaallisut, Greenlandic", NativeName = "kalaallisut, kalaallit oqaasii"},
                    new Language { Id = 75, Code = "kn", Name = "Kannada", NativeName = "ಕನ್ನಡ"},
                    new Language { Id = 76, Code = "kr", Name = "Kanuri", NativeName = "Kanuri"},
                    new Language { Id = 77, Code = "ks", Name = "Kashmiri", NativeName = "कश्मीरी, كشميري‎"},
                    new Language { Id = 78, Code = "kk", Name = "Kazakh", NativeName = "Қазақ тілі"},
                    new Language { Id = 79, Code = "km", Name = "Khmer", NativeName = "ភាសាខ្មែរ"},
                    new Language { Id = 80, Code = "ki", Name = "Kikuyu, Gikuyu", NativeName = "Gĩkũyũ"},
                    new Language { Id = 81, Code = "rw", Name = "Kinyarwanda", NativeName = "Ikinyarwanda"},
                    new Language { Id = 82, Code = "ky", Name = "Kirghiz, Kyrgyz", NativeName = "кыргыз тили"},
                    new Language { Id = 83, Code = "kv", Name = "Komi", NativeName = "коми кыв"},
                    new Language { Id = 84, Code = "kg", Name = "Kongo", NativeName = "KiKongo"},
                    new Language { Id = 85, Code = "ko", Name = "Korean", NativeName = "한국어 (韓國語), 조선말 (朝鮮語)"},
                    new Language { Id = 86, Code = "ku", Name = "Kurdish", NativeName = "Kurdî, كوردی‎"},
                    new Language { Id = 87, Code = "kj", Name = "Kwanyama, Kuanyama", NativeName = "Kuanyama"},
                    new Language { Id = 88, Code = "la", Name = "Latin", NativeName = "latine, lingua latina"},
                    new Language { Id = 89, Code = "lb", Name = "Luxembourgish, Letzeburgesch", NativeName = "Lëtzebuergesch"},
                    new Language { Id = 90, Code = "lg", Name = "Luganda", NativeName = "Luganda"},
                    new Language { Id = 91, Code = "li", Name = "Limburgish, Limburgan, Limburger", NativeName = "Limburgs"},
                    new Language { Id = 92, Code = "ln", Name = "Lingala", NativeName = "Lingála"},
                    new Language { Id = 93, Code = "lo", Name = "Lao", NativeName = "ພາສາລາວ"},
                    new Language { Id = 94, Code = "lt", Name = "Lithuanian", NativeName = "lietuvių kalba"},
                    new Language { Id = 95, Code = "lu", Name = "Luba-Katanga", NativeName = ""},
                    new Language { Id = 96, Code = "lv", Name = "Latvian", NativeName = "latviešu valoda"},
                    new Language { Id = 97, Code = "gv", Name = "Manx", NativeName = "Gaelg, Gailck"},
                    new Language { Id = 98, Code = "mk", Name = "Macedonian", NativeName = "македонски јазик"},
                    new Language { Id = 99, Code = "mg", Name = "Malagasy", NativeName = "Malagasy fiteny"},
                    new Language { Id = 100, Code = "ms", Name = "Malay", NativeName = "bahasa Melayu, بهاس ملايو‎"},
                    new Language { Id = 101, Code = "ml", Name = "Malayalam", NativeName = "മലയാളം"},
                    new Language { Id = 102, Code = "mt", Name = "Maltese", NativeName = "Malti"},
                    new Language { Id = 103, Code = "mi", Name = "Māori", NativeName = "te reo Māori"},
                    new Language { Id = 104, Code = "mr", Name = "Marathi (Marāṭhī)", NativeName = "मराठी"},
                    new Language { Id = 105, Code = "mh", Name = "Marshallese", NativeName = "Kajin M̧ajeļ"},
                    new Language { Id = 106, Code = "mn", Name = "Mongolian", NativeName = "монгол"},
                    new Language { Id = 107, Code = "na", Name = "Nauru", NativeName = "Ekakairũ Naoero"},
                    new Language { Id = 108, Code = "nv", Name = "Navajo, Navaho", NativeName = "Diné bizaad, Dinékʼehǰí"},
                    new Language { Id = 109, Code = "nb", Name = "Norwegian Bokmål", NativeName = "Norsk bokmål"},
                    new Language { Id = 110, Code = "nd", Name = "North Ndebele", NativeName = "isiNdebele"},
                    new Language { Id = 111, Code = "ne", Name = "Nepali", NativeName = "नेपाली"},
                    new Language { Id = 112, Code = "ng", Name = "Ndonga", NativeName = "Owambo"},
                    new Language { Id = 113, Code = "nn", Name = "Norwegian Nynorsk", NativeName = "Norsk nynorsk"},
                    new Language { Id = 114, Code = "no", Name = "Norwegian", NativeName = "Norsk"},
                    new Language { Id = 115, Code = "ii", Name = "Nuosu", NativeName = "ꆈꌠ꒿ Nuosuhxop"},
                    new Language { Id = 116, Code = "nr", Name = "South Ndebele", NativeName = "isiNdebele"},
                    new Language { Id = 117, Code = "oc", Name = "Occitan", NativeName = "Occitan"},
                    new Language { Id = 118, Code = "oj", Name = "Ojibwe, Ojibwa", NativeName = "ᐊᓂᔑᓈᐯᒧᐎᓐ"},
                    new Language { Id = 119, Code = "cu", Name = "Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic", NativeName = "ѩзыкъ словѣньскъ"},
                    new Language { Id = 120, Code = "om", Name = "Oromo", NativeName = "Afaan Oromoo"},
                    new Language { Id = 121, Code = "or", Name = "Oriya", NativeName = "ଓଡ଼ିଆ"},
                    new Language { Id = 122, Code = "os", Name = "Ossetian, Ossetic", NativeName = "ирон æвзаг"},
                    new Language { Id = 123, Code = "pa", Name = "Panjabi, Punjabi", NativeName = "ਪੰਜਾਬੀ, پنجابی‎"},
                    new Language { Id = 124, Code = "pi", Name = "Pāli", NativeName = "पाऴि"},
                    new Language { Id = 125, Code = "fa", Name = "Persian", NativeName = "فارسی"},
                    new Language { Id = 126, Code = "pl", Name = "Polish", NativeName = "polski"},
                    new Language { Id = 127, Code = "ps", Name = "Pashto, Pushto", NativeName = "پښتو"},
                    new Language { Id = 128, Code = "pt", Name = "Portuguese", NativeName = "Português"},
                    new Language { Id = 129, Code = "qu", Name = "Quechua", NativeName = "Runa Simi, Kichwa"},
                    new Language { Id = 130, Code = "rm", Name = "Romansh", NativeName = "rumantsch grischun"},
                    new Language { Id = 131, Code = "rn", Name = "Kirundi", NativeName = "kiRundi"},
                    new Language { Id = 132, Code = "ro", Name = "Romanian, Moldavian, Moldovan", NativeName = "română"},
                    new Language { Id = 133, Code = "ru", Name = "Russian", NativeName = "русский язык"},
                    new Language { Id = 134, Code = "sa", Name = "Sanskrit (Saṁskṛta)", NativeName = "संस्कृतम्"},
                    new Language { Id = 135, Code = "sc", Name = "Sardinian", NativeName = "sardu"},
                    new Language { Id = 136, Code = "sd", Name = "Sindhi", NativeName = "सिन्धी, سنڌي، سندھی‎"},
                    new Language { Id = 137, Code = "se", Name = "Northern Sami", NativeName = "Davvisámegiella"},
                    new Language { Id = 138, Code = "sm", Name = "Samoan", NativeName = "gagana faa Samoa"},
                    new Language { Id = 139, Code = "sg", Name = "Sango", NativeName = "yângâ tî sängö"},
                    new Language { Id = 140, Code = "sr", Name = "Serbian", NativeName = "српски језик"},
                    new Language { Id = 141, Code = "gd", Name = "Scottish Gaelic; Gaelic", NativeName = "Gàidhlig"},
                    new Language { Id = 142, Code = "sn", Name = "Shona", NativeName = "chiShona"},
                    new Language { Id = 143, Code = "si", Name = "Sinhala, Sinhalese", NativeName = "සිංහල"},
                    new Language { Id = 144, Code = "sk", Name = "Slovak", NativeName = "slovenčina"},
                    new Language { Id = 145, Code = "sl", Name = "Slovene", NativeName = "slovenščina"},
                    new Language { Id = 146, Code = "so", Name = "Somali", NativeName = "Soomaaliga, af Soomaali"},
                    new Language { Id = 147, Code = "st", Name = "Southern Sotho", NativeName = "Sesotho"},
                    new Language { Id = 148, Code = "es", Name = "Spanish; Castilian", NativeName = "español, castellano"},
                    new Language { Id = 149, Code = "su", Name = "Sundanese", NativeName = "Basa Sunda"},
                    new Language { Id = 150, Code = "sw", Name = "Swahili", NativeName = "Kiswahili"},
                    new Language { Id = 151, Code = "ss", Name = "Swati", NativeName = "SiSwati"},
                    new Language { Id = 152, Code = "sv", Name = "Swedish", NativeName = "svenska"},
                    new Language { Id = 153, Code = "ta", Name = "Tamil", NativeName = "தமிழ்"},
                    new Language { Id = 154, Code = "te", Name = "Telugu", NativeName = "తెలుగు"},
                    new Language { Id = 155, Code = "tg", Name = "Tajik", NativeName = "тоҷикӣ, toğikī, تاجیکی‎"},
                    new Language { Id = 156, Code = "th", Name = "Thai", NativeName = "ไทย"},
                    new Language { Id = 157, Code = "ti", Name = "Tigrinya", NativeName = "ትግርኛ"},
                    new Language { Id = 158, Code = "bo", Name = "Tibetan Standard, Tibetan, Central", NativeName = "བོད་ཡིག"},
                    new Language { Id = 159, Code = "tk", Name = "Turkmen", NativeName = "Türkmen, Түркмен"},
                    new Language { Id = 160, Code = "tl", Name = "Tagalog", NativeName = "Wikang Tagalog, ᜏᜒᜃᜅ᜔ ᜆᜄᜎᜓᜄ᜔"},
                    new Language { Id = 161, Code = "tn", Name = "Tswana", NativeName = "Setswana"},
                    new Language { Id = 162, Code = "to", Name = "Tonga (Tonga Islands)", NativeName = "faka Tonga"},
                    new Language { Id = 163, Code = "tr", Name = "Turkish", NativeName = "Türkçe"},
                    new Language { Id = 164, Code = "ts", Name = "Tsonga", NativeName = "Xitsonga"},
                    new Language { Id = 165, Code = "tt", Name = "Tatar", NativeName = "татарча, tatarça, تاتارچا‎"},
                    new Language { Id = 166, Code = "tw", Name = "Twi", NativeName = "Twi"},
                    new Language { Id = 167, Code = "ty", Name = "Tahitian", NativeName = "Reo Tahiti"},
                    new Language { Id = 168, Code = "ug", Name = "Uighur, Uyghur", NativeName = "Uyƣurqə, ئۇيغۇرچە‎"},
                    new Language { Id = 169, Code = "uk", Name = "Ukrainian", NativeName = "українська"},
                    new Language { Id = 170, Code = "ur", Name = "Urdu", NativeName = "اردو"},
                    new Language { Id = 171, Code = "uz", Name = "Uzbek", NativeName = "zbek, Ўзбек, أۇزبېك‎"},
                    new Language { Id = 172, Code = "ve", Name = "Venda", NativeName = "Tshivenḓa"},
                    new Language { Id = 173, Code = "vi", Name = "Vietnamese", NativeName = "Tiếng Việt"},
                    new Language { Id = 174, Code = "vo", Name = "Volapük", NativeName = "Volapük"},
                    new Language { Id = 175, Code = "wa", Name = "Walloon", NativeName = "Walon"},
                    new Language { Id = 176, Code = "cy", Name = "Welsh", NativeName = "Cymraeg"},
                    new Language { Id = 177, Code = "wo", Name = "Wolof", NativeName = "Wollof"},
                    new Language { Id = 178, Code = "fy", Name = "Western Frisian", NativeName = "Frysk"},
                    new Language { Id = 179, Code = "xh", Name = "Xhosa", NativeName = "isiXhosa"},
                    new Language { Id = 180, Code = "yi", Name = "Yiddish", NativeName = "ייִדיש"},
                    new Language { Id = 181, Code = "yo", Name = "Yoruba", NativeName = "Yorùbá"},
                    new Language { Id = 182, Code = "za", Name = "Zhuang, Chuang", NativeName = "Saɯ cueŋƅ, Saw cuengh"}
                );
        }
    }
}
